import { generateId } from '../utils/helpers.js';
import { IEntry, EntryFormData } from '../types/index.js';
import { Entity } from './Entity.js';

/**
 * Entry model representing a logged measurement for an Entity
 */
export class Entry implements IEntry {
    id: string;
    entityId: string;
    entityName: string;
    title: string;
    timestamp: string;
    value?: string | number | boolean;
    valueDisplay?: string;
    notes: string;
    latitude?: number;
    longitude?: number;
    locationName?: string;
    isArchived?: boolean;
    createdAt: string;

    constructor(data: Partial<IEntry> & { entityId: string; entityName: string; title: string; timestamp: string }) {
        // ID will be generated by the server if not provided
        this.id = data.id || generateId();
        this.entityId = data.entityId;
        this.entityName = data.entityName;
        this.title = data.title;
        this.timestamp = data.timestamp;
        this.value = data.value;
        this.valueDisplay = data.valueDisplay;
        this.notes = data.notes || '';
        this.latitude = data.latitude;
        this.longitude = data.longitude;
        this.locationName = data.locationName;
        this.isArchived = data.isArchived;
        this.createdAt = data.createdAt || new Date().toISOString();
    }

    static fromFormData(formData: EntryFormData, entity: Entity): Entry {
        return new Entry({
            entityId: entity.id,
            entityName: entity.name,
            title: formData.title,
            timestamp: new Date(formData.timestamp).toISOString(),
            value: formData.value,
            valueDisplay: formData.valueDisplay,
            notes: formData.notes?.trim() || '',
            latitude: formData.latitude,
            longitude: formData.longitude,
            locationName: formData.locationName
        });
    }

    validate(): string[] {
        const errors: string[] = [];

        if (!this.entityId) {
            errors.push('Entity ID is required');
        }

        if (!this.title || this.title.trim() === '') {
            errors.push('Title is required');
        }

        if (!this.timestamp) {
            errors.push('Timestamp is required');
        }

        return errors;
    }

    toJSON(): IEntry {
        return {
            id: this.id,
            entityId: this.entityId,
            entityName: this.entityName,
            title: this.title,
            timestamp: this.timestamp,
            value: this.value,
            valueDisplay: this.valueDisplay,
            notes: this.notes,
            latitude: this.latitude,
            longitude: this.longitude,
            locationName: this.locationName,
            isArchived: this.isArchived,
            createdAt: this.createdAt
        };
    }
}
