import { generateId } from '../utils/helpers.js';
import { ITag, TagType, TagFormData, ValueType, SelectOption, TagProperty } from '../types/index.js';

/**
 * Maps tag types to their default value types
 */
export function getDefaultValueType(tagType: TagType): ValueType {
  const mapping: Record<TagType, ValueType> = {
    'Habit': 'checkbox',         // Binary yes/no tracking
    'Metric': 'number',          // Numeric measurements
    'Task': 'select',            // Status-based workflow
    'Note': 'text',              // Freeform text logging
    'Event': 'datetime-local',   // Time-based occurrences
    'Resource': 'hyperlink',     // External references (URLs)
    'Decision': 'select'         // Choice tracking
  };
  return mapping[tagType];
}

/**
 * Get default options for select value types based on tag type
 */
export function getDefaultSelectOptions(tagType: TagType): SelectOption[] | undefined {
  const optionsMapping: Partial<Record<TagType, SelectOption[]>> = {
    'Task': [
      { value: 'todo', label: 'To Do' },
      { value: 'in-progress', label: 'In Progress' },
      { value: 'done', label: 'Done' }
    ],
    'Decision': [
      { value: 'yes', label: 'Yes' },
      { value: 'no', label: 'No' },
      { value: 'pending', label: 'Pending' }
    ]
  };
  return optionsMapping[tagType];
}

/**
 * Tag model representing a trackable item
 */
export class Tag implements ITag {
  id: string;
  name: string;
  type: TagType;
  categories: string[];
  valueType?: ValueType;
  options?: SelectOption[];
  properties?: TagProperty[];
  createdAt: string;

  constructor(data: Partial<ITag> & { name: string; type: TagType }) {
    // ID will be generated by the server if not provided
    this.id = data.id || generateId();
    this.name = data.name;
    this.type = data.type;
    this.categories = data.categories || [];
    this.valueType = data.valueType;
    this.options = data.options;
    this.properties = data.properties || [];
    this.createdAt = data.createdAt || new Date().toISOString();
  }

  static fromFormData(formData: TagFormData): Tag {
    return new Tag({
      name: formData.name.trim(),
      type: formData.type,
      categories: formData.categories
        ? formData.categories.split(',').map(c => c.trim()).filter(c => c)
        : []
    });
  }

  validate(): string[] {
    const errors: string[] = [];

    if (!this.name) {
      errors.push('Name is required');
    }

    const validTypes: TagType[] = ['Habit', 'Metric', 'Task', 'Note', 'Event', 'Resource', 'Decision'];
    if (!this.type || !validTypes.includes(this.type)) {
      errors.push('Valid type is required');
    }

    return errors;
  }

  toJSON(): ITag {
    return {
      id: this.id,
      name: this.name,
      type: this.type,
      categories: this.categories,
      valueType: this.valueType,
      options: this.options,
      properties: this.properties,
      createdAt: this.createdAt
    };
  }
}
